### PR TITLE
chore: upgrade rector/rector dependency

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Related to https://app.clickup.com/t/1r58kn0

I'm having issues installing the library on msq, this PR should fix the problem

As a reference, the issue I have is the one on the message below (In case you are wondering, yes I tried a few alternatives like the `--ignore-platform-reqs` and `--with-all-dependencies` flags, removing composer.lock, etc

```
- Root composer.json requires arkecosystem/foundation ^0.10.1 -> satisfiable by arkecosystem/foundation[0.10.1].
    - Conclusion: don't install phpstan/phpstan 1.1.2 (conflict analysis result)
    - arkecosystem/foundation 0.10.1 requires rector/rector ^0.11 -> satisfiable by rector/rector[0.11.0, ..., 0.11.60].
    - rector/rector[0.11.54, ..., 0.11.60] require phpstan/phpstan 0.12.99 -> satisfiable by phpstan/phpstan[0.12.99].
    - rector/rector 0.11.53 requires phpstan/phpstan 0.12.98 -> satisfiable by phpstan/phpstan[0.12.98].
    - rector/rector[0.11.50, ..., 0.11.52] require phpstan/phpstan 0.12.96 -> satisfiable by phpstan/phpstan[0.12.96].
    - rector/rector 0.11.49 requires phpstan/phpstan 0.12.95 -> satisfiable by phpstan/phpstan[0.12.95].
    - rector/rector[0.11.43, ..., 0.11.48] require phpstan/phpstan 0.12.94 -> satisfiable by phpstan/phpstan[0.12.94].
    - rector/rector[0.11.39, ..., 0.11.42] require phpstan/phpstan 0.12.93 -> satisfiable by phpstan/phpstan[0.12.93].
    - rector/rector[0.11.36, ..., 0.11.38] require phpstan/phpstan 0.12.91 -> satisfiable by phpstan/phpstan[0.12.91].
    - rector/rector[0.11.21, ..., 0.11.35] require phpstan/phpstan >=0.12.86 <=0.12.90 -> satisfiable by phpstan/phpstan[0.12.86, ..., 0.12.90].
    - rector/rector[0.11.6, ..., 0.11.20] require phpstan/phpstan >=0.12.86 <=0.12.88 -> satisfiable by phpstan/phpstan[0.12.86, 0.12.87, 0.12.88].
    - rector/rector[0.11.0, ..., 0.11.5] require phpstan/phpstan 0.12.86 -> satisfiable by phpstan/phpstan[0.12.86].
    - You can only install one version of a package, so only one of these can be installed: phpstan/phpstan[dev-master, 0.11.6, ..., 0.12.x-dev, 1.0.0, ..., 1.1.2].
    - arkecosystem/foundation 0.10.1 requires phpstan/phpstan ^1.1 -> satisfiable by phpstan/phpstan[1.1.0, 1.1.1, 1.1.2].
    - Conclusion: don't install phpstan/phpstan 1.1.1 (conflict analysis result)
```

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by faustbrian** [comment]
@alfonsobries conflicts

**Comment by alfonsobries** [comment]
@faustbrian ✅

**Comment by faustbrian** [comment]
I see red.

**Comment by alfonsobries** [comment]
🤨 apparently removed a dependency by mistake should work now @faustbrian ✅

**Comment by alfonsobries** [comment]
@faustbrian seems that the release with this change is still missing

**Pull request merged**
