### PR TITLE
refactor: update sidebar styling

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Summary

https://app.clickup.com/t/26gucbv

To test: 

- checkout `refactor/use-foundation-components` on ark.dev (https://github.com/ArkEcosystem/docs/pull/242)
- use `refactor/update-sidebar-styling-tutorial` for foundation
- clear cache
- yarn install & yarn prod
- sidebars should match design

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by ItsANameToo** [comment]
dis still ugly @alexbarnsley 
image

will those lines be fixed in another PR?

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
@alexbarnsley the card mentions both docs and tutorials, but looks like docs has not changed? 
image

**Comment by alexbarnsley** [comment]
@ItsANameToo I thought docs was already correct but I'll double check :thinking:

**Comment by alexbarnsley** [comment]
@ItsANameToo did you clear cache, etc? This is what mine is like locally

image

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
