### PR TITLE
fix: svgs were missing fill="none"

### PR DESCRIPTION
**Pull request by stefro**
## Summary
These icons were introduced for https://app.clickup.com/t/1p68j9h
They were rendering well on icons.html, but not on MSQ. It seemed that adding `fill="none"` solved it.

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [x] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by ItsANameToo** [comment]
@stefro you're adding new icons now instead of updating the existing ones

**Comment by stefro** [comment]
I'm sorry, I should have pulled the renamed ones first. Let me fix that.

**Comment by stefro** [comment]
@ItsANameToo I did add it to the `path` and not the svg element. Could it be that the CI cleanup removes this again? That would explain why they disappeared in your review (and left only the ones I didn't remove).

**Comment by ItsANameToo** [comment]
@stefro yes, workflow will remove them when you add them to both the `path` elements and the `svg` root element. Remove them from the root, add them back to the `path` ones and then the workflow won't remove them

normally having them on the individual elements is obsolete when you have them on the root (hence why the workflow removes them), but it would clash with the way we use the `fill` class in our code

**Comment by stefro** [comment]
Ah, now it makes sense. The Figma export added the fill to the root element. I'll fix it right away!

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
