### PR TITLE
refactor: use separate middleware for `updateProfileInformation` and `updatePasswords`

### PR DESCRIPTION
**Pull request by leMaur**
## Summary
https://app.clickup.com/t/1t7j33v

This PR assigns to `Features::updateProfileInformation` and `Features::updatePasswords` their own middleware set.

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Review by stefro — APPROVED** [review]
Code looks good to me 👍

**Comment by ItsANameToo** [comment]
will this require the other projects that were updated to work with the routes before to be updated again to work with the new config entry @leMaur ?

**Comment by leMaur** [comment]
> will this require the other projects that were updated to work with the routes before to be updated again to work with the new config entry @leMaur ?

@ItsANameToo I'll check our projects and open a PR if needed 👍🏼

**Comment by leMaur** [comment]
Waiting on https://github.com/ArkEcosystem/nodem/pull/310

**Pull request merged**
