### PR TITLE
refactor: update alert component as per new design

### PR DESCRIPTION
**Pull request by leMaur**
## Summary
https://app.clickup.com/t/23yrye8

## TODO
- [x] apply new design
- [x] apply colors for light mode
- [x] apply colors for dark mode
- [x] test responsiveness

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [x] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
image

- it seems the `hint` type does not have proper styling
- we used to have `error` and `danger` that would make use of the same styling, but `danger` seems to have been removed. Can that be re-added to avoid breaking changes?

**Comment by leMaur** [comment]
@ItsANameToo I've checked where "danger" was used and changed to "error". 🤔 on which component did you find that?

**Comment by ItsANameToo** [comment]
@leMaur I based it off the changes. We used to have danger + error, now it's only error
image

**Comment by leMaur** [comment]
@ItsANameToo I've checked other projects and only nodem used "danger". So I refactor it to "error" https://github.com/ArkEcosystem/nodem/pull/340/files#diff-f682ad240b99d1ee4368cbf57ef489771594ad0d66f5b35c9ed2f066aeec4124L9.
But let me know if you prefer to re-add it.

**Comment by ItsANameToo** [comment]
@leMaur I see, that will work, thanks

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
