### PR TITLE
feat: success and info states for table row and roundess

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Related to: https://app.clickup.com/t/1u47hk1

Adds the success (green) and info (primary color) state to the table rows, both used on the  leaderboard table on msq

image

Also updates the row roundess to use 12px according to [this discussion](https://cryptoarkproject.slack.com/archives/CLAGGC7LY/p1637686131490200)

To test: merge this on this PR https://github.com/ArkEcosystem/marketsquare.io/pull/2426/files and go to `/leaderboard` on small screens, you should see the color use

Also considers the dark version:

Regular:
image

Hover:
image

image

Dark:
image

Dark hover (ignore textcolor not part of the table):
image
image

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [X] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by alexbarnsley — APPROVED** [review]
I know you mentioned to ignore dark mode - should that be working at all as part of this task? I've approved on the basis that that will be a different task - might be a question for @ItsANameToo

**Comment by ItsANameToo** [comment]
dark mode is not considered for the task @alexbarnsley

**Comment by alfonsobries** [comment]
I added the dark color because the rest of the states have it, the colors are based on this:
https://www.figma.com/file/o6b1tEMOdUtHv7ijVs6pMX/Payvo-DW?node-id=3%3A60956

**Comment by ItsANameToo** [comment]
yeah it's fine @alfonsobries , just that it doesn't matter for the PR itself at the moment

**Comment by alfonsobries** [comment]
@alexbarnsley I updated this PR to change the roundness on the rows to use 12px (xl) will be great if you can take a look

**Review by alexbarnsley — APPROVED** [review]
It looks beautiful my guy

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
