### PR TITLE
chore: update alpine js to v3

### PR DESCRIPTION
**Pull request by chriship**
## Summary

https://app.clickup.com/t/1kcn1y9

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
Going to request changes on both this and the MSQ PR based on [this](https://github.com/ArkEcosystem/marketsquare.io/pull/2520#pullrequestreview-855886697), as I'm unsure which causes the problem (probably here)

**Comment by ItsANameToo** [comment]
@chriship did you take a look at the comment from @alexbarnsley yet?

**Comment by chriship** [comment]
> @chriship did you take a look at the comment from @alexbarnsley yet?

Ah that one passed me by. Will get onto it today.

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
I'm unable to open the notification dropdown in the navbar @chriship same applies to the profile dropdown. Can you take a look?

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
