### PR TITLE
feat: navbar dark mode

### PR DESCRIPTION
**Pull request by chriship**
## Summary

https://app.clickup.com/t/1ravdvh

Add dark mode css for navbar elements and navbar dropdown elements (tile-link).

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by Highjhacker** [comment]
- Cannot see the `MarketSquare` title within the navbar on dark mode : 


- `Add Project` button (non hovered) doesn't match the design ; 


- Hover effect doesn't match the design ; 


If some of my remarks are out of scope for this PR (cause I see some other ongoing tasks for the navbar dark mode) lemme know :toot:

**Comment by chriship** [comment]
Sorry @Highjhacker I should have mentioned in the PR that it relies on [this PR too](https://github.com/ArkEcosystem/marketsquare.io/pull/2395)

**Review by Highjhacker — APPROVED** [review]
Looking good to me, tried on MSQ with the matching PR and everything looks good 👍

**Comment by ItsANameToo** [comment]
see comments on related MSQ PR

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
