### PR TITLE
[wip] feat: change tippy behaviour on error messages and mobile devices

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

https://app.clickup.com/t/1v0r943

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by alfonsobries** [comment]
@ItsANameToo friendly reminder that we still need to test if this approach works

**Comment by ItsANameToo** [comment]
not forgotten @alfonsobries , will look at this with sam tomorrow

**Comment by alexbarnsley** [comment]
which tomorrow @ItsANameToo? :trollface:

**Comment by ItsANameToo** [comment]
although I think this is a good approach, we'll have to reconsider it again when the need arises. For the current products we don't need it yet with the existing features

**Pull request closed without merging**
