### PR TITLE
feat: add dark mode styles to notifications modal

### PR DESCRIPTION
**Pull request by chriship**
## Summary

https://app.clickup.com/t/1kjfkmm

This PR adds dark mode styles for the notifications modal in the navbar. To test, make some notifications and click on the notification icon in the navbar.

Note: this updates the `no-notifications.svg` from using an img to using the icon component so all sites using `no-notifications.svg` will need to update it's path.

MSQ PR [here](https://github.com/ArkEcosystem/marketsquare.io/pull/2546)

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by leMaur** [comment]
@chriship I found that the button inside the modal is missing the background color on dark mode. It uses `button-secondary` 🤔 not sure it's related to this PR... what do you think?
https://github.com/ArkEcosystem/laravel-foundation/pull/188/files#diff-783b25b1f57061cc51472f80a0c1ce776acb42a709888ccf524de3716c27166dR46

https://user-images.githubusercontent.com/2118799/146147341-cb7e13d0-a57a-40e7-8ba1-2b67e83d0221.mov

**Comment by leMaur** [comment]
@chriship On Figma the background is gray-900 but we use gray-800 and it clash with the text color, see video.

https://user-images.githubusercontent.com/2118799/146149075-71770308-c19a-4aa4-9d22-6b3e5c8c0ad5.mov

🤔 On [Figma](https://github.com/ArkEcosystem/laravel-foundation/pull/188/files#diff-783b25b1f57061cc51472f80a0c1ce776acb42a709888ccf524de3716c27166dR46) the modal is showed on a black background but in reality, most of the pages has bg-gray-800 (see homepage screenshot)

Screenshot 2021-12-15 at 09 22 24

In my opinion making the bg black adds more contrast and helps the modal pop out. @chriship, @ItsANameToo what do you think?

**Comment by ItsANameToo** [comment]
responded on slack, requires more design considerations as gray-800, -900 and black are options used for text and/or backgrounds

**Comment by chriship** [comment]
hmm, yeah something has gone wrong here, modal should be darker with a light 1px border...

**Review by leMaur — APPROVED** [review]
@chriship It's good now! 🚀

**Comment by ItsANameToo** [comment]
It will be useful to move these kind of SVGs to the foundation lib once we are able to adjust the styles on a per-project basis; avoids projects having to keep track of them. Will revisit this at a later time, when it's clear which images can be reused and what kind of differences there are between projects if any

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
