### PR TITLE
fix: problem with custom view finder and numbers

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

The `CommonMarkServiceProvider` register a custom ViewFinder that is causing issues on my PR for updating the explorer dependencies and adding foundation (https://github.com/ArkEcosystem/explorer/pull/968)

Basically, it not loads the class-based components until I remove those lines

The custom class is used to handle views that contain a number like, for example (https://ark.dev/docs/core/releases/upgrade/2.4) the problem is that it was creating conflicts with the Number component that also returned a number 

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by faustbrian** [comment]
As mentioned on Slack, both ark.dev and docs.payvo.com use way more features and the custom view finder is needed for those because Laravel can't handle numerical URLs like https://ark.dev/docs/core/releases/upgrade/2.4. It'll look for a file called `2/4.blade.php` by default instead of `2.4.blade.php` or `2.4/index.blade.php`, which obviously results in a 404.

**Comment by alfonsobries** [comment]
@faustbrian got it, I'll
Update this then

**Comment by alexbarnsley** [comment]
I just changed app.php for my Nodem PR (https://github.com/ArkEcosystem/nodem/pull/274) to use the specific service providers it needs instead of the global foundation one. Wouldn't it just be worth removing the generic one since many projects won't need to load everything in anyway?:

https://github.com/ArkEcosystem/nodem/pull/274/commits/e37f0e2f670342ea21d3a235632d2abf464a04cc

**Comment by alexbarnsley** [comment]
:thinking: what about having a FirstPartyServiceProviders and then the third-party ones need to be explicitly specified?

**Comment by alexbarnsley** [comment]
oh wait, is it commonmark that's failing?

**Comment by alexbarnsley** [comment]
Yeh :thinking: I'm happy to just have to specify each individually if everyone else is. We only need to specify it in one place per project so it's not a major thing if you're okay with it :bleh:

**Comment by alfonsobries** [comment]
@faustbrian just updated this PR,

As context, the problem on explorer is that the `laravel-foundation/src/UserInterface/Components/Number.php` component returns a number like `123,456`. That number was passed as the "name" parameter on the `getPossibleViewFiles` method and it has a match in the regex method

so I updated the view finder to:
1. Match only whole not-formatted numbers with optional decimals like 113.456
2. Since small numbers like 12.33 are formatted like that in the `Number.php` class I'm checking also that the file exists

**Comment by alfonsobries** [comment]
@faustbrian think this was not released (tried with latest version `^0.1.0` and change is not there)

**Comment by faustbrian** [comment]
Should be released in 0.2.0

**Pull request merged**
